apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  resourceName: lwabish-scheduler
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  # kubeconfig路径
  kubeconfig: /Users/xxxxxx/.kube/config
  qps: 50
profiles:
  - pluginConfig:
      - args:
          prometheus_endpoint: localhost:62222
          max_memory: 6
        name: NodeAvailableMemory
    plugins:
      score:
        disabled:
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
          - name: InterPodAffinity
          - name: NodeResourcesLeastAllocated
          - name: NodeAffinity
          - name: NodePreferAvoidPods
          - name: PodTopologySpread
          - name: TaintToleration
        enabled:
          - name: NodeAvailableMemory
            weight: 1
    schedulerName: mem-scheduler

